title: 3D Print Shredder
description: MME Capstone 2023 Project
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
domain: joshferns0212.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://joshferns0212.github.io  # the base hostname and protocol for your site, e.g. http://example.com
